name: FunctAI Schemas Action
run-name: FunctAI detect new schemas by ${{ github.actor }} and will publish to npm soon 🚀
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      schemas: ${{ steps.filter.outputs.schemas }}
      schema_files: ${{ steps.filter.outputs.schemas_files }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          list-files: shell
          predicate-quantifier: "every"
          filters: |
            schemas:
              - \$schemas/**
              - '*.json'
  build_and_commit:
    needs: changes
    if: ${{ needs.changes.outputs.schemas == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          for path in ${{ needs.changes.outputs.schema_files  }}; do
            echo "$path"
          done
  # publish:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.schemas == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
