name: FunctAI Schemas Action
run-name: ${{ github.actor }} detect new schemas and publish it to npm 🚀
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      schemas: ${{ steps.filter.outputs.schemas }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          predicate-quantifier: "every"
          filters: |
            schemas:
              - '$schemas/**'
              - '!**/*.json'
  build_and_commit:
    needs: changes
    if: ${{ needs.changes.outputs.schemas == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          for path in ${{ needs.changes.outputs.schemas }}; do
            echo "$path"
          done
  # publish:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.schemas == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
