name: FunctAI Schema Build and Publish Actions
run-name: FunctAI detect new schemas by ${{ github.actor }} and will publish to npm soon 🚀
on:
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      schemas: ${{ steps.filter.outputs.schemas }}
      schema_files: ${{ steps.filter.outputs.schemas_files }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          list-files: shell
          predicate-quantifier: "every"
          filters: |
            schemas:
              - 'schemas/**/package.json'
  build_and_commit:
    needs: changes
    if: ${{ needs.changes.outputs.schemas == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          paths="${{ needs.changes.outputs.schema_files  }}"
          wd=$( dirname "$PWD" )
          for path in ${paths}; do
            cd $wd
            filedir=$(dirname $path)
            cd $filedir
            npm ci
            npm run build
          done
      - uses: EndBug/add-and-commit@v9
        with:
          message: Format and commit new schema by ${{ github.actor }}
          committer_name: FunctAI
          committer_email: bot@functai.xyz
  publish:
    needs: [changes, build_and_commit]
    if: ${{ needs.changes.outputs.schemas == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: |
          for path in ${{ needs.changes.outputs.schema_files  }}; do
            dir=$(dirname $path)
            cd $dir
            npm publish --access public
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
